name: CD Pipeline
on:
  push:
    tags:
      - 'v**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.ref_name }}
  TOKEN: ${{ secrets.GH_PAT }}
  GITHUB_ACTOR: ${{ github.actor }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-go@v4.0.1
        name: Setup go
        with:
          cache: true
      - run: go version

      - name: run tests
        run: |
          go test -v

  build-image:
    permissions:
      contents: read
      security-events: write
      actions: read
      id-token: write

    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: install docker buildx to build multiple platforms for docker
        uses: docker/setup-buildx-action@v2.0.0
        with:
          install: true

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build, tag, and push docker image to Github registry
        run: |
          docker buildx create --use
          docker buildx  build --platform=linux/amd64 -o type=docker -t $REGISTRY/$IMAGE_NAME:$TAG_NAME .
          docker image tag $REGISTRY/$IMAGE_NAME:$TAG_NAME $REGISTRY/$IMAGE_NAME:amd64 
          docker image tag $REGISTRY/$IMAGE_NAME:$TAG_NAME $REGISTRY/$IMAGE_NAME:latest 
          
          docker push $REGISTRY/$IMAGE_NAME:amd64
          docker push $REGISTRY/$IMAGE_NAME:latest

  build-release-version:
    runs-on: ubuntu-latest
    name: Build release version
    needs:
      - build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}